# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'lendwell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lendwell
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Messaging', '~> 6.3.0'

  post_install do |installer|
    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end
  end

#  target 'lendwell-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

  target 'lendwellTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lendwell-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lendwell-tvOS

  target 'lendwell-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
